name: Run Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ vars.MONGO_URI }}
      MONGO_DB: ${{ vars.MONGO_DB }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Set enviroment variables
        run: export MONGO_URI=${{ vars.MONGO_URI }}
      - name: Build with Maven
        run: mvn package
      - name: Run tests
        run: mvn test
