name: java-maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set enviroment variables
      run: echo "MONGO_URI=${{ vars.MONGO_URI }}" >> $GITHUB_ENV
    - name: Build with Maven
      run: mvn package
